name: Python Data Analysis CI

on:
push:
    branches: [ "main" ]
pull_request:
    branches: [ "main" ]

jobs:
build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
    uses: actions/setup-python@v4
    with:
        python-version: '3.x'  # Specify your Python version
        
    - name: Install dependencies
    run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # If you use Jupyter notebooks:
        pip install jupyter nbconvert
        
    - name: Run tests (if you have any)
    run: |
        python -m pytest
        
    - name: Run static analysis
    run: |
        pip install pylint black
        pylint your_package/
        black --check your_package/
        
    # Add data validation steps if needed
    - name: Run data validation
    run: |
        python scripts/validate_data.py  # Example if you have validation scripts
    
    - name: Build documentation
    run: |
    pip install sphinx
    cd docs && make html
    - name: Deploy docs
    uses: peaceiris/actions-gh-pages@v3
    with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./docs/_build/html

    - name: Cache pip
    uses: actions/cache@v2
    with:
    path: ~/.cache/pip
    key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    restore-keys: |
    ${{ runner.os }}-pip-